routes:
  - name: ErpBridge.Service
    path: /api/erpbridge/
    upstream: http://
  - name: HR.Service
    path: /api/hr/
    upstream: http://
  - name: LoadPlanner3D.Service
    path: /api/loadplanner3d/
    upstream: http://
  - name: OcrDdt.Service
    path: /api/ocrddt/
    upstream: http://
  - name: ServiceRegistry.Service
    path: /api/serviceregistry/
    upstream: http://
  - name: Warehouse.Service
    path: /api/warehouse/
    upstream: http://
